### PR TITLE
Add the euro sign to the end_of_hashtag regex

### PR DESCRIPTION
**Pull request by mrnovalles**

### CODE REVIEW

**Comment by davidpdrsn** [comment]
Change looks good, but I can't merge the PR because I don't have write access to the repo. Can you give me write access or merge the PR yourself? Then I'll publish a new release to crates.io

**Comment by mrnovalles** [comment]
I can't merge it either, but I will let you know as soon as someone does. Thanks

**Comment by davidpdrsn** [comment]
Would it make sense to move the library to my personal github account? Unless you plan on maintaining it going forward.

**Comment by mrnovalles** [comment]
I think you should do that. I won't be able to maintain it moving forward. 
So if you want, please move it to your personal one.

**Comment by davidpdrsn** [comment]
Someone with admin rights on this repo has to do it. I can't do it myself. There is a "transfer repo" button in settings somewhere. I guess either henrik or johnny has admin rights.

**Comment by henrikholm89** [comment]
And hello @davidpdrsn :D

**Comment by mrnovalles** [comment]
Merging this PR, then transferring to my personal account (Github only likes it that way), then moving it towards your way @davidpdrsn

**Pull request merged**
